# Generated by Django 5.1.4 on 2024-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_advuser_fio_advuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
