# Generated by Django 5.1.4 on 2024-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_application_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена'),
        ),
    ]
