# Generated by Django 5.1.4 on 2024-12-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_application_created_at_application_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='price',
        ),
    ]
