# Generated by Django 5.1.4 on 2024-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_application_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
