# Generated by Django 5.1.4 on 2024-12-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
