# Generated by Django 5.1.4 on 2024-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_application_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, upload_to='designs/', verbose_name='Изображение дизайна'),
        ),
        migrations.AlterField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(help_text='Описание', to='catalog.categories'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=100, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('o', 'Принята в работу'), ('d', 'Выполнена')], default='n', help_text='Статус заявки', max_length=1),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
